from mongoengine import *


#Connect mongodb
connect('testdb')

# mongo company model:
class company(Document):
    name = StringField(required=True, max_length=200)
    category_code = StringField(max_length=200)
    crunchbase_url = StringField(max_length=200)
    video_embeds = StringField(max_length=200)
    deadpooled_month = StringField(max_length=200)
    overview = StringField(max_length=200)
    image = StringField(max_length=200)
    updated_at = StringField(max_length=200)
    funding_rounds = StringField(max_length=200)
    total_money_raised = StringField(max_length=200)
    deadpooled_day = StringField(max_length=200)
    email_address = StringField(max_length=200)
    relationships = StringField(max_length=200)
    partners = StringField(max_length=200)
    deadpooled_url = StringField(max_length=200)
    screenshots = StringField(max_length=200)
    founded_day = StringField(max_length=200)
    competitions = StringField(max_length=200)
    blog_feed_url = StringField(max_length=200)
    providerships = StringField(max_length=200)
    products = StringField(max_length=200)
    phone_number = StringField(max_length=200)
    description = StringField(max_length=200)
    founded_year = StringField(max_length=200)
    deadpooled_year = StringField(max_length=200)
    ipo = StringField(max_length=200)
    twitter_username = StringField(max_length=200)
    external_links = StringField(max_length=200)
    number_of_employees = StringField(max_length=200)
    alias_list = StringField(max_length=200)
    acquisitions = StringField(max_length=200)
    permalink = StringField(max_length=200)
    milestones = StringField(max_length=200)
    founded_month = StringField(max_length=200)
    created_at = StringField(max_length=200)
    homepage_url = StringField(max_length=200)
    offices = StringField(max_length=200)
    blog_url = StringField(max_length=200)
    tag_list = StringField(max_length=200)
    investments = StringField(max_length=200)
    acquisition = StringField(max_length=200)
